version: 2.1

jobs:
  build_and_push:
    # job to build aws ecr ami image
    docker:
      - image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/devops/packer:1.6.1
    working_directory: ~/aws_ecr_ami
    steps:
      - checkout:
          path: ~/aws_ecr_ami
      - run:
          name: Prepare env for build
          command: echo 'export BUILD_TAG="${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}-$(git rev-parse --verify HEAD | cut -c1-8)"' >> ${BASH_ENV}
      - run:
          name: Build eks ami
          command: "echo Build tag variable value: ${BUILD_TAG}, circle sha1: ${CIRCLE_SHA1}"
      - run:
          name: Push eks ami to aws
          command: "aws s3 ls"
      - run:
          name: Notify after build
          command: "echo TODO: prepare notification step"

workflows:
  aws_eks_ami:
    jobs:
      - build_and_push:
          context: CICD
