version: 2.1

jobs:
  prepare_env:
    # job to prepare build environment
    docker:
      - image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/devops/packer:1.6.1
    working_directory: ~/aws_ecr_ami
    steps:
      - checkout:
          path: ~/aws_ecr_ami
      - run:
          name: Prepare env for build
          command: echo 'export BUILD_TAG="${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}-$(git rev-parse --verify HEAD | cut -c1-8)"' >> ${BASH_ENV}
      - run:
          name: Install requirements
          command: apk add make
  validate:
    # job to validate aws ecr ami image
    docker:
      - image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/devops/packer:1.6.1
    steps:
      - attach_workspace:
            at: .
      - run:
          name: Packer Validate
          command: make -e all-validate
  build:
    # job to build aws ecr ami image
    docker:
      - image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/devops/packer:1.6.1
    steps:
      - attach_workspace:
            at: .
      - run:
          name: Packer build
          command: make -e all
      - run:
          name: Notify after build
          command: "echo TODO: finish datadog integration"

workflows:
  aws_eks_ami:
    jobs:
      - prepare_env:
          context: CICD
      - validate:
          context: CICD
          requires:
            - prepare_env
      - build:
          context: CICD
          requires:
            - validate
#          filters:
#            branches:
#              only:
#                - master
