version: 2.1

executors:
  packer:
    docker:
      - image: 411466821576.dkr.ecr.us-west-2.amazonaws.com/devops/ci/packer:1.11.0

# workflow jobs definition
jobs:
  prepare_env:
    # job to prepare build environment
    executor: packer
    working_directory: ~/aws_ecr_ami
    steps:
      - checkout:
          path: ~/aws_ecr_ami
      - persist_to_workspace:
          root: "~"
          paths:
            - aws_ecr_ami
  build:
    executor: packer
    environment:
      K8S_VERSION: 1.26
      kubernetes_version: 1.26
      os_distro: "al2023"
      kubernetes_build_date: "2024-03-14"
    steps:
      - attach_workspace:
            at: .
      - run:
          name: Prepare BUILD_TAG env
          command: |
            NORMALIZED_BRANCH_NAME=$(echo ${CIRCLE_BRANCH} | sed 's/[^a-zA-Z0-9]/-/g' | cut -c 1-50)
            echo "export BUILD_TAG=${NORMALIZED_BRANCH_NAME}-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1::7}" >> ${BASH_ENV}
            AMI_NAME="amazon-eks-node-${K8S_VERSION}-$(date '+%Y-%m-%d')-test-${CIRCLE_BUILD_NUM}"
            echo "export AMI_NAME=${AMI_NAME}" >> ${BASH_ENV}
      - run:
          name: Install aws cli
          command: apk add aws-cli
      - run:
          name: Install dependency for packer
          command: cd aws_ecr_ami && packer plugins install github.com/hashicorp/amazon
      - run:
          name: Packer validate and build AMI
          # AWS sometimes take really long to finish ami build.
          # By default, Circle CI have 10 minutes timeout without response,
          # so we must extend that timeout limit to be sure that ami build can pass
          no_output_timeout: 60m
          #command: cd aws_ecr_ami && PACKER_VARIABLE_FILE=fluence-eks-worker-al2-variables.json make -e -j2 ${K8S_VERSION}
          command: cd aws_ecr_ami && PACKER_VARIABLE_FILE=fluence-eks-worker-al2-variables.json make -e -j2 validate
workflows:
  aws_eks_ami:
    jobs:
      - prepare_env:
          context: AWS_OPERATIONS_DEV_0
      - build:
          name: build main
          context:
            - AWS_OPERATIONS_0
            - PACKER_OPERATIONS_0
          requires:
            - prepare_env
          filters:
            branches:
              only:
                - main
      - build:
          name: build dev
          context:
            - AWS_OPERATIONS_DEV_0
            - PACKER_OPERATIONS_DEV_0
          requires:
            - prepare_env
          # filters:
          #   branches:
          #     only:
          #       - dev
