version: 2.1

jobs:
  prepare_env:
    # job to prepare build environment
    docker:
      - image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/devops/ci-packer:latest
    working_directory: ~/aws_ecr_ami
    steps:
      - checkout:
          path: ~/aws_ecr_ami
      - run:
          name: Prepare env for build
          command: echo 'export BUILD_TAG="${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}-$(git rev-parse --verify HEAD | cut -c1-8)"' >> ${BASH_ENV}
  validate:
    # job to validate aws ecr ami image
    docker:
      - image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/devops/ci-packer:latest
    working_directory: ~/aws_ecr_ami
    steps:
      - attach_workspace:
            at: .
      - checkout:
          path: ~/aws_ecr_ami
      - run:
          name: Packer Validate
          command: make -e -j2 all-validate
  build:
    # job to build aws ecr ami image
    docker:
      - image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/devops/ci-packer:latest
    working_directory: ~/aws_ecr_ami
    steps:
      - attach_workspace:
            at: .
      - checkout:
          path: ~/aws_ecr_ami
      - run:
          name: Packer build
          # AWS sometimes take really long to finish ami build.
          # By default, Crircle CI have 10 minutes timeout without response,
          # so we must extend that timeout limit to be sure that ami build can pass
          no_output_timeout: 60m
          command: make -e -j2 all
      - run:
          name: Notify after build
          command: "echo TODO: finish datadog integration"

workflows:
  aws_eks_ami:
    jobs:
      - prepare_env:
          context: CICD
      - validate:
          context: CICD
          requires:
            - prepare_env
      - build:
          context: CICD
          requires:
            - validate
          filters:
            branches:
              only:
                - master
